name: Stress
version: '1.0'
main: me.revqz.stress.Stress
api-version: '1.21'
author: revqz
softdepend: [ProtocolLib]

commands:
  stopwatch:
    description: Countdown timer (Stopwatch).
    usage: /stopwatch <seconds>
  benchmark:
    description: Run a benchmark (Benchmark)
    usage: /benchmark <seconds>
  stress:
    description: Run a stress test.
    usage: /stress <test_name>
