name: Stress
version: '1.0'
main: me.revqz.stress.Stress
api-version: '1.21'
author: revqz

commands:
  stopwatch:
    description: Countdown timer.
    usage: /stopwatch <seconds>
  benchmark:
    description: Run metric benchmark.
    usage: /benchmark <seconds>
  stress:
    description: Run a named stress test.
    usage: /stress <test_name>
